source "https://rubygems.org"

gem 'cucumber'
gem 'capybara'
gem 'poltergeist', '>= 1.8.1'
gem 'rspec'
gem 'phantomjs'
gem 'phantomjs-binaries'
gem 'selenium-webdriver', '2.45.0'
gem 'show_me_the_cookies'
gem 'yard-cucumber'
