---
kind: pipeline
name: default
type: kubernetes

environment:
  APP_NAME: appeal-rights-exhausted
  PROD_ENV: are
  STG_ENV: are-stg
  UAT_ENV: are-uat
  BRANCH_ENV: are-branch
  PRODUCTION_URL: www.appeal-rights-exhausted.homeoffice.gov.uk
  IMAGE_URL: quay.io/ukhomeofficedigital
  IMAGE_REPO: are-app
  GIT_REPO: UKHomeOffice/AppealRightsExhausted
  HOF_CONFIG: hof-services-config/Appeal_Rights_Exhausted
  NON_PROD_AVAILABILITY: Mon-Fri 08:00-23:00 Europe/London
  READY_FOR_TEST_DELAY: 20s
  NOTIFY_STUB: stub

trigger:
  branch:
    - feature/*
    - master

linting: &linting
  pull: if-not-exists
  image: node:20
  environment:
    NOTIFY_KEY: USE_MOCK
  commands:
    - yarn run test:lint

unit_tests: &unit_tests
  pull: if-not-exists
  image: node:20
  environment:
    NOTIFY_KEY: USE_MOCK
  commands:
    - yarn run test:unit

sonar_scanner: &sonar_scanner
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner-nodejs:latest
  commands:
    - sonar-scanner -Dproject.settings=./sonar-project.properties

acceptance_tests: &acceptance_tests
  pull: if-not-exists
  image: mcr.microsoft.com/playwright:v1.12.3-focal

steps:

  - name: scan-image-official
    image: aquasec/trivy:latest
    volumes:
      - name: dockersock
        path: /drone/src/run
    commands:
      -  trivy image -f json -o /drone/src/run/trivy-report.json  node:20.17.0-alpine3.20@sha256:2cc3d19887bfea8bf52574716d5f16d4668e35158de866099711ddfb2b16b6e0

  - name: send-to-slack
    image: alpine:latest
    volumes:
      - name: dockersock
        path: /drone/src/run
    environment:
      SLACK_WEBHOOK_URL:
        from_secret: slack_sas_hof_security_webhook
    commands:
      - echo "🔍 Installing dependencies..."
      - apk add --no-cache curl
      - echo "🔍 Checking Trivy report file..."
      - ls -l /drone/src/run
      - cat /drone/src/run/trivy-report.json || echo "❌ No vulnerabilities found or report is empty!"
      - |
        if [ -s /drone/src/run/trivy-report.json ]; then
          # Extract total number of vulnerabilities
          VULNERABILITIES=$(grep -o '"VulnerabilityID":' /drone/src/run/trivy-report.json | wc -l)
          echo "🔍 Found $VULNERABILITIES vulnerabilities..."

          if [ "$VULNERABILITIES" -gt 0 ]; then
            # Extract vulnerabilities: CVE ID, Severity, and Package Name
            VULN_LIST=$(grep -o '"VulnerabilityID": *"[^"]*"' /drone/src/run/trivy-report.json | awk -F'"' '{print $4}' | paste -sd '\n' -)
            SEVERITIES=$(grep -o '"Severity": *"[^"]*"' /drone/src/run/trivy-report.json | awk -F'"' '{print $4}' | paste -sd '\n' -)
            PACKAGES=$(grep -o '"PkgName": *"[^"]*"' /drone/src/run/trivy-report.json | awk -F'"' '{print $4}' | paste -sd '\n' -)

            # Create formatted vulnerability message
            REPORT="⚠️ *Trivy Scan Report* 🚨\nVulnerabilities Found: $VULNERABILITIES\n\n"
            REPORT+="\`\`\`\nCVE - SEVERITY - PACKAGE\n"
            paste -d' - ' <(echo "$VULN_LIST") <(echo "$SEVERITIES") <(echo "$PACKAGES") >> report.txt
            cat report.txt >> slack_message.txt
            echo -e "\n\`\`\`" >> slack_message.txt

            # Send Slack notification
            curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"$(cat slack_message.txt)\"}" "$SLACK_WEBHOOK_URL" || echo "❌ Failed to send Slack notification!"
          else
            echo "✅ No vulnerabilities found!"
            curl -X POST -H 'Content-type: application/json' --data '{"text": "✅ No vulnerabilities found in the Trivy scan!"}' "$SLACK_WEBHOOK_URL"
          fi
        else
          echo "❌ Trivy report is missing or empty!"
        fi


  - name: clone_repos
    image: alpine/git
    environment:
      DRONE_GIT_USERNAME:
        from_secret: drone_git_username
      DRONE_GIT_TOKEN:
        from_secret: drone_git_token
    commands:
      - git clone https://$${DRONE_GIT_USERNAME}:$${DRONE_GIT_TOKEN}@github.com/UKHomeOfficeForms/hof-services-config.git
    when:
      branch:
        include:
        - master
        - feature/*
      event: [push, pull_request]

  - name: setup_deploy
    pull: if-not-exists
    image: node:20
    environment:
      NOTIFY_KEY: USE_MOCK
    commands:
      - yarn install --frozen-lockfile
      - yarn run postinstall
    when:
      branch:
        include:
        - master
      event: push

  - name: linting_deploy
    <<: *linting
    when:
      branch:
        include:
          - master
      event: push

  - name: unit_tests_deploy
    <<: *unit_tests
    when:
      branch:
        include:
          - master
      event: push

  - name: sonar_scanner_deploy
    <<: *sonar_scanner
    when:
      branch:
        include:
          - master
      event: push

  - name: build_image
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker build --no-cache -t $${IMAGE_REPO}:$${DRONE_COMMIT_SHA} .
    volumes:
      - name: dockersock
        path: /drone/src/run
    when:
      branch: master
      event: [push, pull_request]

  - name: image_to_quay
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
    - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
    - docker login -u="ukhomeofficedigital+are" -p=$${DOCKER_PASSWORD} quay.io
    - docker tag $${IMAGE_REPO}:$${DRONE_COMMIT_SHA} $${IMAGE_URL}/$${IMAGE_REPO}:$${DRONE_COMMIT_SHA}
    - docker push $${IMAGE_URL}/$${IMAGE_REPO}:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: [push, pull_request]

# Trivy Security Scannner
  - name: scan-image
    pull: always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      IMAGE_NAME: are-app:${DRONE_COMMIT_SHA}
      SEVERITY: MEDIUM,HIGH,CRITICAL
      FAIL_ON_DETECTION: false
      IGNORE_UNFIXED: true
      ALLOW_CVE_LIST_FILE: hof-services-config/Appeal_Rights_Exhausted/trivy-cve-exceptions.txt
    when:
      event:
      - pull_request
      - push
      - tag

  # Deploy to pull request UAT environment
  - name: deploy_to_branch
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      # NOTIFY_STUB: stub
      KUBE_SERVER:
        from_secret: kube_server_dev
      KUBE_TOKEN:
        from_secret: kube_token_sas_dev
    commands:
      - bin/deploy.sh $${BRANCH_ENV}
    when:
      branch: master
      event: pull_request

  - name: setup_branch
    pull: if-not-exists
    image: node:20
    environment:
      NOTIFY_KEY: USE_MOCK
    commands:
      - yarn install --frozen-lockfile
      - yarn run postinstall
    when:
      branch:
        include:
          - master
          - feature/*
      event: pull_request

  - name: linting_branch
    <<: *linting
    when:
      branch:
        include:
          - master
          - feature/*
      event: pull_request

  - name: unit_tests_branch
    <<: *unit_tests
    when:
      branch:
        include:
        - master
        - feature/*
      event: pull_request

  - name: sonar_scanner_branch
    <<: *sonar_scanner
    when:
      branch:
        include:
          - master
          - feature/*
      event: pull_request

  - name: build_acceptance_branch
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker build -f Dockerfile-acceptance -t acceptance-$${DRONE_COMMIT_SHA} .
    when:
      branch:
        include:
          - master
          - feature/*
      event: pull_request

  - name: test_acceptance_branch
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
    - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
    - docker run -d --name=redis-$${DRONE_COMMIT_SHA} redis
    - docker run -d -e NODE_ENV=ci -e DISABLE_CSP=true --name=app-$${DRONE_COMMIT_SHA} --net=container:redis-$${DRONE_COMMIT_SHA} $${IMAGE_REPO}:$${DRONE_COMMIT_SHA}
    - docker run --rm --net=container:app-$${DRONE_COMMIT_SHA} acceptance-$${DRONE_COMMIT_SHA}
    - docker rm -vf "app-$${DRONE_COMMIT_SHA}" "redis-$${DRONE_COMMIT_SHA}"
    when:
      branch:
        include:
          - master
          - feature/*
      event: pull_request

  # Snyk security scans which run after branch deployment to prevent blocking of PR UAT tests
  - name: snyk_scan
    pull: if-not-exists
    image: node:20
    environment:
      SNYK_TOKEN:
        from_secret: snyk_token
    commands:
      - yarn run test:snyk
    when:
      branch:
        include:
          - master
          - feature/*
      event: pull_request


  # # TEST Deploy to Master UAT environment
  # - name: TEST_deploy_to_uat
  #   pull: if-not-exists
  #   image: quay.io/ukhomeofficedigital/kd:v1.14.0
  #   environment:
  #     KUBE_SERVER:
  #       from_secret: kube_server_dev
  #     KUBE_TOKEN:
  #       from_secret: kube_token_sas_dev
  #   commands:
  #     - bin/deploy.sh $${UAT_ENV}
  #   when:
  #     branch: master
  #     event: pull_request
  #
  # # TEST Deploy to Master STG environment
  # - name: TEST_deploy_to_stg
  #   pull: if-not-exists
  #   image: quay.io/ukhomeofficedigital/kd:v1.14.0
  #   environment:
  #     KUBE_SERVER:
  #       from_secret: kube_server_stg
  #     KUBE_TOKEN:
  #       from_secret: kube_token_stg
  #   commands:
  #     - bin/deploy.sh $${STG_ENV}
  #   when:
  #     branch: master
  #     event: pull_request

  # Deploy to Master UAT environment
  - name: deploy_to_uat
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      KUBE_SERVER:
        from_secret: kube_server_dev
      KUBE_TOKEN:
        from_secret: kube_token_sas_dev
    commands:
      - bin/deploy.sh $${UAT_ENV}
    when:
      branch: master
      event: push

  - name: build_acceptance_deploy
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker build -f Dockerfile-acceptance -t acceptance-$${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: push

  - name: test_acceptance_deploy
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
    - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
    - docker run -d --name=redis-$${DRONE_COMMIT_SHA} redis
    - docker run -d -e NODE_ENV=ci -e DISABLE_CSP=true --name=app-$${DRONE_COMMIT_SHA} --net=container:redis-$${DRONE_COMMIT_SHA} $${IMAGE_REPO}:$${DRONE_COMMIT_SHA}
    - docker run --rm --net=container:app-$${DRONE_COMMIT_SHA} acceptance-$${DRONE_COMMIT_SHA}
    - docker rm -vf "app-$${DRONE_COMMIT_SHA}" "redis-$${DRONE_COMMIT_SHA}"
    when:
      branch: master
      event: push

  # Get pull request branch so correct PR UAT environment is torn down in the tear_down_branch step that follows
  - name: get_pr_branch
    pull: if-not-exists
    image: drone/cli:alpine@sha256:14409f7f7247befb9dd2effdb2f61ac40d1f5fbfb1a80566cf6f2f8d21f3be11
    environment:
      DRONE_SERVER:
        from_secret: drone_server
      DRONE_TOKEN:
        from_secret: drone_token
    volumes:
      - name: dockersock
        path: /root/.dockersock
    commands:
      - drone build info $GIT_REPO $DRONE_BUILD_NUMBER --format {{.Message}} | grep -o '[^ ]\+$' -m1 | sed 's|UKHomeOffice/||g' | tr '[:upper:]' '[:lower:]' | tr '/' '-' > /root/.dockersock/branch_name.txt
    when:
      branch: master
      event: push

  # Tear down pull request UAT environment
  - name: tear_down_branch
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      KUBE_SERVER:
        from_secret: kube_server_dev
      KUBE_TOKEN:
        from_secret: kube_token_sas_dev
    volumes:
      - name: dockersock
        path: /root/.dockersock
    commands:
      - bin/deploy.sh tear_down
    when:
      branch: master
      event: push

    # Deploy to Staging environment
  - name: deploy_to_stg
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      KUBE_SERVER:
        from_secret: kube_server_stg
      KUBE_TOKEN:
        from_secret: kube_token_stg
    commands:
      - bin/deploy.sh $${STG_ENV}
    when:
      branch: master
      event: push

  # Checks a build being promoted has passed, is on master which effectively means a healthy build on Staging
  - name: sanity_check_build_prod
    pull: if-not-exists
    image: drone/cli:alpine@sha256:14409f7f7247befb9dd2effdb2f61ac40d1f5fbfb1a80566cf6f2f8d21f3be11
    environment:
      DRONE_SERVER:
        from_secret: drone_server
      DRONE_TOKEN:
        from_secret: drone_token
    commands:
      - bin/sanity_check_build.sh
    when:
      target: PROD
      event: promote

  - name: clone_repos_prod
    image: alpine/git
    environment:
      DRONE_GIT_USERNAME:
        from_secret: drone_git_username
      DRONE_GIT_TOKEN:
        from_secret: drone_git_token
    commands:
      - git clone https://$${DRONE_GIT_USERNAME}:$${DRONE_GIT_TOKEN}@github.com/UKHomeOfficeForms/hof-services-config.git
    when:
      target: PROD
      event: promote

    # Deploy to Production environment
  - name: deploy_to_prod
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      KUBE_SERVER:
        from_secret: kube_server_prod
      KUBE_TOKEN:
        from_secret: kube_token_prod
    commands:
      - bin/deploy.sh $${PROD_ENV}
    when:
      target: PROD
      event: promote

# CRON job step that tears down our pull request UAT environments
  - name: cron_tear_down
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      KUBE_SERVER:
        from_secret: kube_server_dev
      KUBE_TOKEN:
        from_secret: kube_token_sas_dev
    commands:
      - bin/clean_up.sh $${BRANCH_ENV}
    when:
      cron: tear_down_pr_envs
      event: cron

  # CRON job steps that runs security scans using Snyk & Trivy
  - name: cron_clone_repos
    image: alpine/git
    environment:
      DRONE_GIT_USERNAME:
        from_secret: drone_git_username
      DRONE_GIT_TOKEN:
        from_secret: drone_git_token
    commands:
      - git clone https://$${DRONE_GIT_USERNAME}:$${DRONE_GIT_TOKEN}@github.com/UKHomeOfficeForms/hof-services-config.git
    when:
      cron: security_scans
      event: cron

  - name: cron_build_image
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - docker build --no-cache -t $${IMAGE_REPO}:$${DRONE_COMMIT_SHA} .
    volumes:
      - name: dockersock
        path: /drone/src/run
    when:
      cron: security_scans
      event: cron

  - name: cron_snyk_scan
    pull: if-not-exists
    image: node:20
    environment:
      SNYK_TOKEN:
        from_secret: snyk_token
    commands:
      - yarn install --frozen-lockfile
      - yarn run postinstall
      - yarn run test:snyk
    when:
      cron: security_scans
      event: cron

  - name: cron_trivy_scan
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    pull: always
    environment:
        IMAGE_NAME: are-app:${DRONE_COMMIT_SHA}
        SEVERITY: MEDIUM,HIGH,CRITICAL
        FAIL_ON_DETECTION: false
        IGNORE_UNFIXED: true
        ALLOW_CVE_LIST_FILE: hof-services-config/Appeal_Rights_Exhausted/trivy-cve-exceptions.txt
    when:
      cron: security_scans
      event: cron
 

  # Slack notification upon a CRON job fail
  - name: cron_notify_slack_tear_down_pr_envs
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: sas-build
      failure: ignore
      icon_url: http://readme.drone.io/0.5/logo_dark.svg
      icon.url: http://readme.drone.io/0.5/logo_dark.svg
      template: "CRON Job {{build.deployTo}} of Appeal Rights Exhausted has {{build.status}} - <{{build.link}}|#{{build.number}}> {{#success build.status}}\n  :thumbsup: :thumbsup: :thumbsup:\n{{else}}\n  :x: :x: :x:\n{{/success}} Author: {{build.author}}\n\nDuration: {{since job.started}}\n\nJob: <{{build.link}}|#{{build.number}}>\n\nCommit: {{build.commit}}\n"
      username: Drone
      webhook:
        from_secret: slack_webhook
    when:
      cron: tear_down_pr_envs
      event: cron
      status: failure

  - name: cron_notify_slack_security_scans
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: sas-build
      failure: ignore
      icon_url: http://readme.drone.io/0.5/logo_dark.svg
      icon.url: http://readme.drone.io/0.5/logo_dark.svg
      template: "CRON Job {{build.deployTo}} of Appeal Rights Exhausted has {{build.status}} - <{{build.link}}|#{{build.number}}> {{#success build.status}}\n  :thumbsup: :thumbsup: :thumbsup:\n{{else}}\n  :x: :x: :x:\n{{/success}} Author: {{build.author}}\n\nDuration: {{since job.started}}\n\nJob: <{{build.link}}|#{{build.number}}>\n\nCommit: {{build.commit}}\n"
      username: Drone
      webhook:
        from_secret: slack_webhook
    when:
      cron: security_scans
      event: cron
      status: failure

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

  # Redis session setup in background so integration tests can run
  - name: session
    image: redis
    volumes:
      - name: dockersock
        path: /drone/src/run

volumes:
  - name: dockersock
    temp: {}

...
