FROM ruby:3.0

COPY acceptance_tests /code
WORKDIR /code

ENV BUNDLER_VERSION 2.3.15
RUN gem update --system \
    && gem install bundler -v $BUNDLER_VERSION \
    && bundle config set --local deployment 'true' \
    && bundle lock --add-platform x86_64-linux \
    && bundle install

ENTRYPOINT "cucumber"
