apiVersion: v1
kind: Service
metadata:
 labels:
   name: are
 name: are
spec:
 type: NodePort
 ports:
   - name: http
     port: 8080
     targetPort: 8080
     nodePort: 30301 
   - name: https
     port: 8080
     targetPort: 8080
     nodePort: 30302
 selector:
   name: are
