---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-error-pages
data:
  error-429.html: |
    <html>
    <head>
      <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Too Many Requests</title>
          <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            padding: 50px;
        }
        h1 {
            color: #ff6347;
        }
          </style>
    </head>
      <body>
        <h1>Rate Limit Exceeded</h1>
        <p>Please try again later.</p>
      </body>
    </html>
