apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: branch-tls-internal
  labels:
    cert-manager.io/solver: route53
spec:
  commonName: "*.internal.{{ .BRANCH_ENV }}.homeoffice.gov.uk"
  dnsNames:
  - "*.internal.{{ .BRANCH_ENV }}.homeoffice.gov.uk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: branch-tls-internal
