apiVersion: v1
kind: Service
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  labels:
    name: redis-{{ .DRONE_SOURCE_BRANCH }}
    service: redis-{{ .DRONE_SOURCE_BRANCH }}
  name: redis-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  labels:
    name: redis
    service: redis
  name: redis
  {{ end }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: redis-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: redis
    {{ end }}
