apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: redis-pvc-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: redis-pvc
  {{ end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
      storage: 10Gi
      {{ else }}
      storage: 1Gi
      {{ end }}
  storageClassName: redis-manual
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  volumeName: redis-pv-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  volumeName: redis-pv
  {{ end }}
